-- 默认使用 sql="sql" 格式
INSERT INTO library (lang, lb_id, difficulty, page, title, tags, summary, content, eg_in, eg_out) VALUES 
('python', 46, 'beginner', 1, '创建列表', '["列表","创建"]', '学习如何创建和初始化 Python 列表。', '列表是 Python 中可变的有序序列。可以使用方括号 [] 或 list() 函数创建。\\n示例：my_list = [1, 2, 3] 或 empty_list = list()。', '["my_list = [1, 2, 3]", "empty_list = []", "list_from_range = list(range(5))"]', '["[1, 2, 3]", "[]", "[0, 1, 2, 3, 4]"]'),
('python', 47, 'beginner', 1, '访问列表元素', '["列表","索引"]', '使用索引访问列表中的元素。', '列表索引从 0 开始，可以使用正索引和负索引访问元素。\\n例如，list[0] 访问第一个元素，list[-1] 访问最后一个元素。', '["my_list = [\\"a\\", \\"b\\", \\"c\\"]\\nprint(my_list[0])", "print(my_list[-1])"]', '["\\"a\\"", "\\"c\\""]'),
('python', 48, 'beginner', 1, '列表切片操作', '["列表","切片"]', '使用切片获取列表的子集。', '切片语法为 list[start:stop:step]，可以获取列表的一部分。start 包含，stop 不包含。', '["numbers = [0, 1, 2, 3, 4]\\nprint(numbers[1:4])", "print(numbers[:3])", "print(numbers[::2])"]', '["[1, 2, 3]", "[0, 1, 2]", "[0, 2, 4]"]'),
('python', 49, 'beginner', 1, '向列表添加元素 - append', '["列表","方法"]', '使用 append() 方法在列表末尾添加元素。', 'append() 方法将元素添加到列表的末尾，修改原列表。', '["my_list = [1, 2]\\nmy_list.append(3)\\nprint(my_list)"]', '["[1, 2, 3]"]'),
('python', 50, 'beginner', 1, '扩展列表 - extend', '["列表","方法"]', '使用 extend() 方法将另一个列表的元素添加到当前列表。', 'extend() 方法将可迭代对象的元素逐个添加到列表末尾。', '["list1 = [1, 2]\\nlist2 = [3, 4]\\nlist1.extend(list2)\\nprint(list1)"]', '["[1, 2, 3, 4]"]'),
('python', 51, 'beginner', 1, '在指定位置插入元素 - insert', '["列表","方法"]', '使用 insert() 方法在列表的指定位置插入元素。', 'insert(index, element) 在索引位置插入元素，原有元素后移。', '["my_list = [1, 3]\\nmy_list.insert(1, 2)\\nprint(my_list)"]', '["[1, 2, 3]"]'),
('python', 52, 'beginner', 1, '删除列表元素 - remove 和 pop', '["列表","方法"]', '学习使用 remove() 和 pop() 方法删除列表元素。', 'remove(value) 删除第一个匹配的元素，pop(index) 删除指定索引的元素并返回它。', '["list = [1, 2, 3, 2]\\nlist.remove(2)\\nprint(list)", "list = [1, 2, 3]\\nelement = list.pop(1)\\nprint(element, list)"]', '["[1, 3, 2]", "2 [1, 3]"]'),
('python', 53, 'beginner', 1, '列表排序', '["列表","排序"]', '使用 sort() 和 sorted() 对列表进行排序。', 'sort() 方法原地排序列表，sorted() 函数返回排序后的新列表。', '["numbers = [3, 1, 4, 2]\\nnumbers.sort()\\nprint(numbers)", "numbers = [3, 1, 4, 2]\\nsorted_numbers = sorted(numbers)\\nprint(sorted_numbers, numbers)"]', '["[1, 2, 3, 4]", "[1, 2, 3, 4] [3, 1, 4, 2]"]'),
('python', 54, 'beginner', 1, '列表推导式基础', '["列表","推导式"]', '使用列表推导式简洁地创建列表。', '列表推导式提供了一种从可迭代对象创建列表的简洁方式。语法：[expression for item in iterable]。', '["squares = [x**2 for x in range(5)]\\nprint(squares)", "evens = [x for x in range(10) if x % 2 == 0]\\nprint(evens)"]', '["[0, 1, 4, 9, 16]", "[0, 2, 4, 6, 8]"]'),
('python', 55, 'beginner', 1, '创建字典', '["字典","创建"]', '学习如何创建和初始化 Python 字典。', '字典是键值对的无序集合。可以使用花括号 {} 或 dict() 函数创建。', '["my_dict = {\\"name\\": \\"Alice\\", \\"age\\": 25}", "empty_dict = {}", "dict_from_list = dict([(\\"a\\", 1), (\\"b\\", 2)])"]', '["{\\"name\\": \\"Alice\\", \\"age\\": 25}", "{}", "{\\"a\\": 1, \\"b\\": 2}"]'),
('python', 56, 'beginner', 1, '访问字典键值对', '["字典","访问"]', '使用键访问字典中的值。', '可以通过键直接访问值，如 dict[key]。如果键不存在，会引发 KeyError。', '["person = {\\"name\\": \\"Bob\\", \\"age\\": 30}\\nprint(person[\\"name\\"])", "print(person.get(\\"age\\"))"]', '["\\"Bob\\"", "30"]'),
('python', 57, 'beginner', 1, '安全访问字典 - get 方法', '["字典","方法"]', '使用 get() 方法安全地访问字典值。', 'get(key, default) 返回键对应的值，如果键不存在则返回默认值。', '["scores = {\\"math\\": 90, \\"science\\": 85}\\nprint(scores.get(\\"math\\", 0))", "print(scores.get(\\"history\\", \\"Not found\\"))"]', '["90", "\\"Not found\\""]'),
('python', 58, 'beginner', 1, '获取字典的键、值、项', '["字典","方法"]', '使用 keys(), values(), items() 方法获取字典的组成部分。', '这些方法返回视图对象，可以转换为列表进行查看。', '["data = {\\"a\\": 1, \\"b\\": 2}\\nprint(list(data.keys()))", "print(list(data.values()))", "print(list(data.items()))"]', '["[\\"a\\", \\"b\\"]", "[1, 2]", "[(\\"a\\", 1), (\\"b\\", 2)]"]'),
('python', 59, 'beginner', 1, '更新字典 - update 方法', '["字典","方法"]', '使用 update() 方法合并字典或添加键值对。', 'update() 方法用另一个字典的键值对更新当前字典。', '["dict1 = {\\"a\\": 1}\\ndict2 = {\\"b\\": 2}\\ndict1.update(dict2)\\nprint(dict1)", "dict1.update({\\"c\\": 3})\\nprint(dict1)"]', '["{\\"a\\": 1, \\"b\\": 2}", "{\\"a\\": 1, \\"b\\": 2, \\"c\\": 3}"]'),
('python', 60, 'beginner', 1, '字典推导式基础', '["字典","推导式"]', '使用字典推导式简洁地创建字典。', '字典推导式语法：{key_expr: value_expr for item in iterable}。', '["squares = {x: x**2 for x in range(5)}\\nprint(squares)", "even_squares = {x: x**2 for x in range(10) if x % 2 == 0}\\nprint(even_squares)"]', '["{0: 0, 1: 1, 2: 4, 3: 9, 4: 16}", "{0: 0, 2: 4, 4: 16, 6: 36, 8: 64}"]');