-- Using default sql="sql" as format not specified by user
INSERT INTO library (lang, lb_id, difficulty, page, title, tags, summary, content, eg_in, eg_out) VALUES
('python', 16, 'beginner', 1, 'if 语句基础', '["if","条件判断"]', '学习如何使用 if 语句进行条件判断。', 'if 语句用于根据条件执行代码块。语法为：if condition: 后跟缩进的代码块。如果条件为 True，则执行代码块；否则跳过。\n示例：判断一个数是否为正数。', '["x = 5\\nif x > 0:\\n    print(\\"正数\\")"]', '["正数"]'),
('python', 17, 'beginner', 1, 'if-else 语句', '["if","else","条件判断"]', '使用 if-else 语句处理两种可能情况。', 'if-else 语句允许在条件为 True 时执行一个代码块，为 False 时执行另一个代码块。\n语法：if condition: ... else: ...', '["x = -3\\nif x > 0:\\n    print(\\"正数\\")\\nelse:\\n    print(\\"非正数\\")"]', '["非正数"]'),
('python', 18, 'beginner', 1, 'if-elif-else 语句', '["if","elif","else","多条件"]', '使用 if-elif-else 处理多个条件分支。', 'if-elif-else 语句用于多个条件检查。从上到下评估条件，第一个为 True 的块被执行，如果没有条件为 True 且存在 else，则执行 else 块。\n语法：if condition1: ... elif condition2: ... else: ...', '["x = 0\\nif x > 0:\\n    print(\\"正数\\")\\nelif x < 0:\\n    print(\\"负数\\")\\nelse:\\n    print(\\"零\\")"]', '["零"]'),
('python', 19, 'beginner', 1, '嵌套条件语句', '["嵌套","条件判断"]', '在条件语句内部使用另一个条件语句。', '嵌套条件语句是指在一个条件代码块内再使用 if 或其他条件语句。这允许更复杂的逻辑判断。\n注意缩进以确保代码块正确。', '["x = 10\\nif x > 0:\\n    if x % 2 == 0:\\n        print(\\"正偶数\\")\\n    else:\\n        print(\\"正奇数\\")\\nelse:\\n    print(\\"非正数\\")"]', '["正偶数"]'),
('python', 20, 'beginner', 1, '比较运算符', '["比较运算符","条件"]', '学习用于条件判断的比较运算符。', '比较运算符用于比较两个值，返回布尔值 True 或 False。包括：==（等于）、!=（不等于）、>（大于）、<（小于）、>=（大于等于）、<=（小于等于）。\n示例：使用比较运算符检查变量。', '["a = 5\\nb = 3\\nprint(a > b)\\nprint(a == b)"]', '["True\\nFalse"]'),
('python', 21, 'beginner', 1, '逻辑运算符 and', '["逻辑运算符","and","条件组合"]', '使用 and 运算符组合多个条件。', 'and 运算符用于组合多个条件，只有当所有条件都为 True 时，整个表达式才为 True。\n语法：condition1 and condition2', '["age = 25\\nif age >= 18 and age <= 60:\\n    print(\\"成年人\\")"]', '["成年人"]'),
('python', 22, 'beginner', 1, '逻辑运算符 or', '["逻辑运算符","or","条件组合"]', '使用 or 运算符组合多个条件。', 'or 运算符用于组合多个条件，只要有一个条件为 True，整个表达式就为 True。\n语法：condition1 or condition2', '["score = 85\\nif score >= 90 or score < 60:\\n    print(\\"需要关注\\")\\nelse:\\n    print(\\"良好\\")"]', '["良好"]'),
('python', 23, 'beginner', 1, '逻辑运算符 not', '["逻辑运算符","not","条件取反"]', '使用 not 运算符取反条件。', 'not 运算符用于取反一个布尔条件，将 True 变为 False，False 变为 True。\n语法：not condition', '["is_rainy = False\\nif not is_rainy:\\n    print(\\"晴天\\")"]', '["晴天"]'),
('python', 24, 'beginner', 1, '条件表达式（三元运算符）', '["三元运算符","条件表达式"]', '学习使用条件表达式进行简洁的条件赋值。', '条件表达式，也称为三元运算符，允许在一行中根据条件选择值。语法：value_if_true if condition else value_if_false。\n示例：根据条件设置变量。', '["x = 10\\ny = \\"正数\\" if x > 0 else \\"非正数\\"\\nprint(y)"]', '["正数"]'),
('python', 25, 'beginner', 1, '布尔值 True 和 False', '["布尔值","条件基础"]', '理解布尔值在条件判断中的作用。', '在 Python 中，条件判断依赖于布尔值 True 和 False。许多表达式和函数返回布尔值，直接用于条件语句。\n示例：使用布尔变量。', '["flag = True\\nif flag:\\n    print(\\"标志为真\\")"]', '["标志为真"]'),
('python', 26, 'beginner', 1, '空值判断', '["None","空值","条件判断"]', '学习如何判断变量是否为空值 None。', 'None 是 Python 中表示空值的特殊对象。在条件判断中，None 被视为 False。可以使用 is 或 == 检查 None。\n示例：检查变量是否为 None。', '["value = None\\nif value is None:\\n    print(\\"值为空\\")"]', '["值为空"]'),
('python', 27, 'beginner', 1, '简单条件应用：奇偶判断', '["应用","奇偶判断"]', '应用条件判断检查一个数是奇数还是偶数。', '使用模运算符 % 检查一个数除以 2 的余数，如果余数为 0 则为偶数，否则为奇数。\n这是一个常见的条件判断应用。', '["num = 7\\nif num % 2 == 0:\\n    print(\\"偶数\\")\\nelse:\\n    print(\\"奇数\\")"]', '["奇数"]'),
('python', 28, 'beginner', 1, '多个条件组合使用', '["条件组合","逻辑运算"]', '结合使用 and、or 和 not 处理复杂条件。', '在实际编程中，经常需要组合多个条件。使用括号来明确优先级，避免歧义。\n示例：检查年龄和分数。', '["age = 20\\nscore = 75\\nif (age >= 18 and age <= 25) or score > 80:\\n    print(\\"符合条件\\")\\nelse:\\n    print(\\"不符合\\")"]', '["符合条件"]'),
('python', 29, 'beginner', 1, '条件语句中的代码块', '["代码块","缩进"]', '理解条件语句中代码块的重要性和缩进规则。', '在 Python 中，代码块通过缩进来定义。条件语句后的代码必须正确缩进，通常使用 4 个空格。\n错误缩进会导致语法错误或逻辑错误。', '["x = 5\\nif x > 0:\\n    print(\\"正数\\")\\n    print(\\"执行完毕\\")  # 正确缩进\\nprint(\\"外部代码\\")  # 不在条件块内"]', '["正数\\n执行完毕\\n外部代码"]'),
('python', 30, 'beginner', 1, '常见错误：使用 = 代替 ==', '["常见错误","语法"]', '避免在条件判断中错误使用赋值运算符 = 而不是比较运算符 ==。', '一个常见错误是在条件中使用单个等号 = 进行赋值，而不是双等号 == 进行比较。这可能导致意外行为，因为赋值表达式会返回赋值后的值。\n示例：演示错误和正确用法。', '["x = 5\\nif x = 3:  # 错误：使用 =\\n    print(\\"错误\\")\\n# 正确：\\nif x == 3:\\n    print(\\"等于 3\\")\\nelse:\\n    print(\\"不等于 3\\")"]', '["不等于 3"]');