USE `study_app`;
-- 默认输出格式为 SQL
INSERT INTO library (lang, lb_id, difficulty, page, title, tags, summary, content, eg_in, eg_out) VALUES
('python', 61, 'beginner', 1, '函数定义', '["函数","定义"]', '介绍如何使用 def 关键字定义函数。', '在 Python 中，函数通过 def 关键字定义。定义包括函数名、参数列表和函数体。函数体是缩进的代码块。定义函数后，可以通过函数名调用它。\n示例：def say_hello():\n    print("Hello!")\n这定义了一个名为 say_hello 的函数，调用时将打印 "Hello!"。', '["def say_hello():\\n    print(\\"Hello!\\")\\nsay_hello()", "def add(x, y):\\n    return x + y\\nresult = add(3, 4)\\nprint(result)"]', '["Hello!", "7"]'),
('python', 62, 'beginner', 1, '函数调用', '["函数","调用"]', '学习如何调用已定义的函数。', '调用函数意味着执行函数体内的代码。调用函数时使用函数名后跟圆括号，圆括号内可以传递参数。如果函数有返回值，调用表达式的结果就是返回值。\n例如，对于函数 def greet(name): print(f"Hello, {name}!"),调用 greet("Alice") 将执行打印语句。', '["def greet(name):\\n    print(f\\"Hello, {name}!\\")\\ngreet(\\"Bob\\")", "def multiply(a, b):\\n    return a * b\\nproduct = multiply(5, 6)\\nprint(product)"]', '["Hello, Bob!", "30"]'),
('python', 63, 'beginner', 1, '函数参数', '["函数","参数"]', '了解函数参数的基本概念。', '函数参数是传递给函数的值，用于函数内部计算。参数在定义时指定，在调用时提供。参数可以是必需参数，意味着调用时必须提供。\n示例：def power(base, exponent): return base ** exponent，这里 base 和 exponent 是参数。', '["def power(base, exponent):\\n    return base ** exponent\\nprint(power(2, 3))", "def introduce(name, age):\\n    print(f\\"My name is {name}, I am {age} years old.\\")\\nintroduce(\\"Charlie\\", 25)"]', '["8", "My name is Charlie, I am 25 years old."]'),
('python', 64, 'beginner', 1, '函数返回值', '["函数","返回值"]', '学习函数如何使用 return 语句返回值。', '函数可以通过 return 语句返回一个值给调用者。如果没有 return 语句，函数默认返回 None。返回值可以用于赋值或进一步计算。\n示例：def square(n): return n * n，调用 square(4) 返回 16。', '["def square(n):\\n    return n * n\\nprint(square(5))", "def get_greeting():\\n    return \\"Hello, World!\\"\\nmessage = get_greeting()\\nprint(message)"]', '["25", "Hello, World!"]'),
('python', 65, 'beginner', 1, '局部与全局变量', '["变量","作用域"]', '理解函数内变量的作用域。', '在函数内部定义的变量是局部变量，只在函数内可见。在函数外部定义的变量是全局变量，可以在函数内访问，但如果要修改，需要使用 global 关键字。\n示例：x = 10  # 全局变量\ndef func():\n    y = 5  # 局部变量\n    print(x)  # 可以访问全局变量\nfunc()', '["x = 10\\ndef show_x():\\n    print(x)\\nshow_x()", "def set_local():\\n    local_var = 20\\n    print(local_var)\\nset_local()"]', '["10", "20"]'),
('python', 66, 'beginner', 1, '默认参数', '["函数","默认参数"]', '学习如何为函数参数设置默认值。', '默认参数允许在定义函数时为参数指定默认值。如果调用时不提供该参数，则使用默认值。默认参数必须在非默认参数之后。\n示例：def greet(name, greeting="Hello"): print(f"{greeting}, {name}!")，调用 greet("Alice") 使用默认 greeting。', '["def greet(name, greeting=\\"Hello\\"):\\n    print(f\\"{greeting}, {name}!\\")\\ngreet(\\"Bob\\")", "def greet(name, greeting=\\"Hello\\"):\\n    print(f\\"{greeting}, {name}!\\")\\ngreet(\\"Charlie\\", \\"Hi\\")"]', '["Hello, Bob!", "Hi, Charlie!"]'),
('python', 67, 'beginner', 1, '关键字参数', '["函数","关键字参数"]', '学习如何使用关键字参数调用函数。', '关键字参数允许在调用函数时通过参数名指定值，这样可以不按顺序传递参数。使用关键字参数可以提高代码可读性。\n示例：def introduce(name, age): print(f"Name: {name}, Age: {age}")\n调用 introduce(age=25, name="Alice") 即使顺序颠倒也能正确工作。', '["def introduce(name, age):\\n    print(f\\"Name: {name}, Age: {age}\\")\\nintroduce(age=30, name=\\"Bob\\")", "def power(base, exponent):\\n    return base ** exponent\\nprint(power(exponent=3, base=2))"]', '["Name: Bob, Age: 30", "8"]'),
('python', 68, 'beginner', 1, '可变参数', '["函数","可变参数"]', '了解如何使用 *args 接收任意数量的位置参数。', '可变参数允许函数接受任意数量的位置参数。在定义函数时，使用 *args 作为参数，args 是一个元组，包含所有额外位置参数。\n示例：def sum_all(*numbers): return sum(numbers)\n调用 sum_all(1,2,3,4) 返回 10。', '["def sum_all(*args):\\n    return sum(args)\\nprint(sum_all(1, 2, 3))", "def print_args(*args):\\n    for arg in args:\\n        print(arg)\\nprint_args(\\"a\\", \\"b\\", \\"c\\")"]', '["6", "a\\nb\\nc"]'),
('python', 69, 'beginner', 1, '匿名函数 lambda', '["函数","lambda"]', '学习使用 lambda 表达式创建匿名函数。', 'lambda 表达式用于创建小型匿名函数。它只能包含一个表达式，并返回该表达式的结果。语法：lambda arguments: expression。常用于需要函数对象的地方。\n示例：square = lambda x: x * x，调用 square(5) 返回 25。', '["square = lambda x: x * x\\nprint(square(4))", "add = lambda a, b: a + b\\nprint(add(10, 20))", "sorted_list = sorted([(1, \\"b\\"), (2, \\"a\\")], key=lambda x: x[1])\\nprint(sorted_list)"]', '["16", "30", "[(2, \\"a\\"), (1, \\"b\\")]"]'),
('python', 70, 'beginner', 1, '函数文档字符串', '["函数","文档字符串"]', '学习如何为函数添加文档字符串以提供说明。', '文档字符串是函数定义后的第一个字符串，用于描述函数功能。可以通过 __doc__ 属性访问。使用三重引号编写多行文档字符串。\n示例：def add(a, b):\n    """返回两个数的和。"""\n    return a + b', '["def multiply(a, b):\\n    \\"\\"\\"This function multiplies two numbers.\\n    Args:\\n        a: first number\\n        b: second number\\n    Returns:\\n        The product of a and b.\\n    \\"\\"\\"\\n    return a * b\\nprint(multiply.__doc__)\\nprint(multiply(3, 4))"]', '["This function multiplies two numbers.\\n    Args:\\n        a: first number\\n        b: second number\\n    Returns:\\n        The product of a and b.\\n", "12"]'),
('python', 71, 'beginner', 1, '递归函数', '["函数","递归"]', '介绍递归函数的基本概念。', '递归函数是调用自身的函数。必须有基线条件来终止递归，否则会导致无限递归。常用于解决分治问题，如阶乘、斐波那契数列。\n示例：def factorial(n):\n    if n == 1:\n        return 1\n    else:\n        return n * factorial(n-1)', '["def factorial(n):\\n    if n == 1:\\n        return 1\\n    else:\\n        return n * factorial(n-1)\\nprint(factorial(5))", "def fibonacci(n):\\n    if n <= 1:\\n        return n\\n    else:\\n        return fibonacci(n-1) + fibonacci(n-2)\\nprint(fibonacci(6))"]', '["120", "8"]'),
('python', 72, 'beginner', 1, '函数作用域', '["函数","作用域"]', '深入了解函数内变量的作用域规则。', 'Python 使用 LEGB 规则查找变量：Local、Enclosing、Global、Built-in。在函数内，局部变量优先。使用 global 和 nonlocal 关键字修改外部变量。\n示例：x = 10\ndef func():\n    x = 5  # 局部变量\n    print(x)\nfunc()\nprint(x)  # 输出全局 x', '["x = 10\\ndef func():\\n    x = 5\\n    print(\\"Inside:\\", x)\\nfunc()\\nprint(\\"Outside:\\", x)", "def outer():\\n    y = 20\\n    def inner():\\n        nonlocal y\\n        y = 30\\n        print(\\"Inner:\\", y)\\n    inner()\\n    print(\\"Outer:\\", y)\\nouter()"]', '["Inside: 5\\nOutside: 10", "Inner: 30\\nOuter: 30"]'),
('python', 73, 'beginner', 1, '内置函数', '["函数","内置函数"]', '学习一些常用的 Python 内置函数。', 'Python 提供了许多内置函数，如 print(), len(), type(), str(), int() 等，可以直接使用无需定义。了解这些函数有助于高效编程。\n示例：print(len([1,2,3])) 输出 3。', '["print(len(\\"Hello\\"))", "numbers = [1, 2, 3, 4, 5]\\nprint(sum(numbers))", "print(type(42))"]', '["5", "15", "<class \\"int\\">"]'),
('python', 74, 'beginner', 1, '函数作为对象', '["函数","一等公民"]', '理解函数在 Python 中是一等对象。', '在 Python 中，函数是对象，可以赋值给变量、作为参数传递、作为返回值返回。这允许高阶函数和函数式编程风格。\n示例：def greet(): print("Hi")\nmy_func = greet\nmy_func()  # 调用函数', '["def shout(text):\\n    return text.upper()\\nprint(shout(\\"hello\\"))\\nyell = shout\\nprint(yell(\\"world\\"))", "def apply_func(func, value):\\n    return func(value)\\ndef square(x):\\n    return x * x\\nprint(apply_func(square, 5))"]', '["HELLO", "WORLD", "25"]'),
('python', 75, 'beginner', 1, '错误处理', '["函数","错误处理"]', '学习在函数中使用 try-except 处理错误。', '在函数中可以使用 try-except 块来捕获和处理异常，防止程序崩溃。这对于健壮的函数设计很重要。\n示例：def safe_divide(a, b):\n    try:\n        return a / b\n    except ZeroDivisionError:\n        return "Cannot divide by zero"', '["def safe_divide(a, b):\\n    try:\\n        return a / b\\n    except ZeroDivisionError:\\n        return \\"Error: Division by zero\\"\\nprint(safe_divide(10, 2))\\nprint(safe_divide(10, 0))", "def convert_to_int(s):\\n    try:\\n        return int(s)\\n    except ValueError:\\n        return \\"Invalid input\\"\\nprint(convert_to_int(\\"123\\"))\\nprint(convert_to_int(\\"abc\\"))"]', '["5.0", "Error: Division by zero", "123", "Invalid input"]');